-- ========================================
-- Warehouse Management System - SQL Setup
-- ========================================
-- Create users table for login authentication

-- For Oracle Database:
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'USER',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Insert sample admin user (plaintext password for demo - use bcrypt in production)
INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'ADMIN');
INSERT INTO users (username, password, role) VALUES ('user1', 'user123', 'USER');

COMMIT;

-- ========================================
-- For MySQL Database (alternative):
-- ========================================
-- CREATE TABLE users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(100) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     role VARCHAR(50) DEFAULT 'USER',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- 
-- INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'ADMIN');
-- INSERT INTO users (username, password, role) VALUES ('user1', 'user123', 'USER');
-- 

-- ========================================
-- For H2 Database (embedded/testing):
-- ========================================
-- CREATE TABLE users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(100) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     role VARCHAR(50) DEFAULT 'USER',
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- 
-- INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'ADMIN');
-- INSERT INTO users (username, password, role) VALUES ('user1', 'user123', 'USER');
-- 
